version: '3.7'

services:
  app:
    image: php:7.4-fpm
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    networks:
      - web-network

  mysql:
    image: mysql:8.0
    container_name: mysql_sv
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: khoaidz
      MYSQL_DATABASE: restaurant
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - web-network

  nginx:
    image: nginx:latest
    container_name: nginx-web
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - web-network

networks:
  web-network:

volumes:
  mysql-db-volume:
